name: HaxxServer
version: 1.1
description: Haxx Server Backend
author: EssexIO
main: me.Haxx.HaxxServer.Main
 
permissions:
    bcolors.use:
        description: Allows player to see plugin list.
        default: op